# Generated by Django 2.2.5 on 2019-09-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('senha', models.CharField(blank=True, max_length=255, null=True)),
                ('razaoSocial', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=255, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('responsavel', models.CharField(max_length=255, verbose_name='Responsavel')),
                ('tipo', models.CharField(choices=[('frigorifico', 'Frigorífico'), ('associacao', 'Associação'), ('cooperativa', 'Cooperativa'), ('instituicaoPublica', 'Instituição Pública')], max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(max_length=255, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('is_superuser', models.NullBooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
                'ordering': ['email'],
            },
        ),
    ]
