# Generated by Django 2.2.5 on 2019-09-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20190930_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='is_staff',
            field=models.NullBooleanField(default=False),
        ),
    ]
