# Generated by Django 2.2.5 on 2019-09-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idApi', models.IntegerField(verbose_name='ID da aplicação anterior')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('nomeProprietario', models.CharField(max_length=40, verbose_name='Nome do Proprietário')),
                ('qtdAtual', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantidade atual de Kg na Propriedade')),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
                'ordering': ['nome'],
            },
        ),
    ]
